name: GitHub Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bitshield
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Beirut
          config_animations: yes
          config_display: large
          
          # 3D Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Language Stats
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          
          # Coding Habits (Time Charts)
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14
          
          # Technology Icons
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 20
          
          # Projects
          plugin_projects: yes
          plugin_projects_limit: 4
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
