name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bitshield
          
          template: classic
          base: header, activity, community, repositories
          
          config_timezone: Asia/Beirut
          config_animations: yes
          config_display: large
          config_padding: 6%, 12%
          
          # Animated Contribution Snake
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_days: 90
          
          # Rainbow Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_colors: rainbow
          plugin_languages_limit: 12
          plugin_languages_sections: most-used, recently-used
          
          # Skyline 3D
          plugin_skyline: yes
          plugin_skyline_year: current-year
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_compatibility: yes
          
          # Reactions
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          plugin_reactions_display: absolute
