name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bitshield
          template: classic
          base: header, repositories
          config_timezone: Asia/Beirut
          config_display: large
          config_animations: yes
          config_order: base.header, isocalendar, languages, habits, topics, base.repositories
          
          # 3D Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Languages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_colors: github
          
          # Coding Habits
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
          
          # Technology Icons
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 20
